# Generated by Django 5.1.2 on 2025-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
                ('gmap', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Unapproved', 'Unapproved'), ('Recent', 'Recent'), ('Trending', 'Trending'), ('Featured', 'Featured'), ('Latest', 'Latest'), ('Most_viewed', 'Most_Viewed'), ('Popular', 'Popular'), ('top', 'top'), ('new', 'new')], default='Unapproved', max_length=100),
        ),
    ]
